/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.darkwaterkiller;

import java.io.*;
import java.util.Scanner;

import com.google.gson.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //gson obj for JSON manipulation
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        //make new obj and then turn it into a JSON string
        SimpleObject so1 = new SimpleObject(1, "Hunter", "The developer of this code.", new int[]{3, 5, 67, 2, 45,6});
        String jsonString = gson.toJson(so1);

        //writing JSON to a file
        BufferedWriter bw;
        try{
            bw = new BufferedWriter(new FileWriter("./src/main/java/io/github/darkwaterkiller/jsonTest.json"));//open
            bw.write(jsonString);//write
            bw.close();//close
        }catch(Exception e) {
            System.err.println("Could not open file");
            return;
        }

        //reading JSON from a file
        Scanner input;
        String readJSON = "";
        try{
            input = new Scanner(new File("./src/main/java/io/github/darkwaterkiller/jsonTestInput.json"));//open
            while(input.hasNext()) //while not EOF
                readJSON += input.nextLine();//read
            input.close();//close
        }catch(Exception e) {
            System.err.println("Could not open input file");
            return;
        }
        //shove data into obj
        SimpleObject soFromFile = gson.fromJson(readJSON, SimpleObject.class);
        System.out.println(soFromFile);//print to console
    }
}
