/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.darkwaterkiller;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EtchedBorder;

public class App extends JFrame {

    private GroupLayout mainLayout;

    public App() {


        initComponents();
    }

    private void initComponents() {
        
    }

    public static void main(String[] args) {
        //Attempt to set the UI's look to the OS default
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e) {
            System.err.println("Unable to set look and feel");
        }

        //Launch the poker app
        SwingUtilities.invokeLater(()->new App());
    }
}
